# Global Setting for the Database
# PageSize, StartRID, etc..
PAGE_SIZE = 4096
COL_DATA_SIZE = 8
BASE_CONST = 1
TAIL_CONST = 40
TAIL_MERGE_CONST = 1
METADATA_COLS = 4
START_RID = 0
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
BUFFER_POOL_SIZE_RANGE = 20